### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
# one_hot = one hot representation
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [16]:
# One hot Represenation -- index from dictionary
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9139, 9541, 2775, 6662], [9139, 9541, 2775, 6725], [9139, 2836, 2775, 642], [3128, 8220, 2325, 4510, 6167], [3128, 8220, 2325, 4510, 8604], [687, 9139, 8170, 2775, 9584], [4504, 6196, 5742, 4510]]


### Word Embedding Represntation

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [19]:
import numpy as np

In [23]:
sent_length=7
#embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[9139 9541 2775 6662    0    0    0]
 [9139 9541 2775 6725    0    0    0]
 [9139 2836 2775  642    0    0    0]
 [3128 8220 2325 4510 6167    0    0]
 [3128 8220 2325 4510 8604    0    0]
 [ 687 9139 8170 2775 9584    0    0]
 [4504 6196 5742 4510    0    0    0]]


In [25]:
# Adding max no of features should be their 
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
# adam optimizer & Mean Squared Error
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 7, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [36]:
#embedded_docs[-1::]
embedded_docs[1::3]

array([[9139, 9541, 2775, 6725,    0,    0,    0],
       [3128, 8220, 2325, 4510, 8604,    0,    0]], dtype=int32)

In [41]:
# Low dimensional (Embedding Matrix)
# Embedding Matrix
# voc_size = 10000, dimensions = 10 | 2000 ---->> dimensions of 10 vectors
print(model.predict(embedded_docs))

[[[ 0.02408214  0.04682999  0.02939847 -0.01723992 -0.02241713
    0.03390559 -0.04589422  0.00569101 -0.04839909  0.04564809]
  [ 0.03326755 -0.02125721 -0.00011165  0.00423777  0.03475342
    0.02632828 -0.00557493 -0.0220847   0.0147432  -0.04473735]
  [-0.03944888  0.00422219  0.01047049  0.0011642   0.02443499
   -0.04237005 -0.0418934  -0.04343424 -0.04372932 -0.01120623]
  [-0.03073147 -0.02608451  0.02174271 -0.03149775 -0.00353688
    0.03620019  0.04040258  0.04531536  0.01548577 -0.0063105 ]
  [ 0.04025618  0.01263681  0.02955865  0.02622714  0.04293752
   -0.00611278 -0.02202038 -0.01272684  0.01486001 -0.02245448]
  [ 0.04025618  0.01263681  0.02955865  0.02622714  0.04293752
   -0.00611278 -0.02202038 -0.01272684  0.01486001 -0.02245448]
  [ 0.04025618  0.01263681  0.02955865  0.02622714  0.04293752
   -0.00611278 -0.02202038 -0.01272684  0.01486001 -0.02245448]]

 [[ 0.02408214  0.04682999  0.02939847 -0.01723992 -0.02241713
    0.03390559 -0.04589422  0.00569101 -0.0483

In [42]:
embedded_docs[0]

array([9139, 9541, 2775, 6662,    0,    0,    0], dtype=int32)

In [43]:
print(model.predict(embedded_docs)[0])

[[ 0.02408214  0.04682999  0.02939847 -0.01723992 -0.02241713  0.03390559
  -0.04589422  0.00569101 -0.04839909  0.04564809]
 [ 0.03326755 -0.02125721 -0.00011165  0.00423777  0.03475342  0.02632828
  -0.00557493 -0.0220847   0.0147432  -0.04473735]
 [-0.03944888  0.00422219  0.01047049  0.0011642   0.02443499 -0.04237005
  -0.0418934  -0.04343424 -0.04372932 -0.01120623]
 [-0.03073147 -0.02608451  0.02174271 -0.03149775 -0.00353688  0.03620019
   0.04040258  0.04531536  0.01548577 -0.0063105 ]
 [ 0.04025618  0.01263681  0.02955865  0.02622714  0.04293752 -0.00611278
  -0.02202038 -0.01272684  0.01486001 -0.02245448]
 [ 0.04025618  0.01263681  0.02955865  0.02622714  0.04293752 -0.00611278
  -0.02202038 -0.01272684  0.01486001 -0.02245448]
 [ 0.04025618  0.01263681  0.02955865  0.02622714  0.04293752 -0.00611278
  -0.02202038 -0.01272684  0.01486001 -0.02245448]]
